### ISSUE TITLE
program does not work when no prior Slack installation exists

### ISSUE THREAD

**Issue by andikay** [crazy-max/slack-portable#1]
The program never starts, because the folders and subsequent files in the path **/Slack Portable/data/storage/slack-settings** do not exist. Log file says the following:

INFO - Creating symlink...
INFO - Checking downloads folder...
INFO - Updating Slack settings...
WARN - Slack settings not found in: C:/Users/USERNAME/Documents/Data/Slack Portable/data/storage/slack-settings

**Comment by crazy-max** [comment]
Hi,

I have updated the [installation part](https://github.com/crazy-max/slack-portable#installation) of the README. Do you download the `slack-portable.exe` or one of the `.7z` / `.zip` archives ?

**Comment by andikay** [comment]
I downloaded the full 72 MB .zip archive, unpacked it and ran slack-portable.exe – and then my mentioned problem came up.

**Comment by crazy-max** [comment]
Ok thanks for your feedback i will investigate on this!

**Comment by crazy-max** [comment]
Ok i have the same behavior

**Comment by crazy-max** [comment]
Solved in the latest release
