### ISSUE TITLE
program starts, but Windows message says it crashed

### ISSUE THREAD

**Issue by andikay** [crazy-max/slack-portable#2]
Downloaded newest .zip (slack-portable-2.6.0-beta189985592-7.zip), extracted it, started slack-portable.exe. Result: the program works, but at the same time a Windows message says that "Slack crashed!" and it stays in the front, so I cannot use Slack, I just see that it runs behind the crash message.

The log file does not show any errors, the final message in the log file is: "INFO - Launch Slack..."

OS: Win7 64bit, latest updates of course

**Comment by crazy-max** [comment]
It's a behavior with the latest beta from slack. I will implement a new feature today.
Thanks for your feedback!

**Comment by crazy-max** [comment]
Solved in the latest release : https://github.com/crazy-max/slack-portable/releases/latest

**Comment by crazy-max** [comment]
@andikay It's ok now ?

**Comment by andikay** [comment]
Yes it works now, thanks a lot!

**Comment by crazy-max** [comment]
Ok thanks!
