### ISSUE TITLE
New instance opened with Windows notification method

### ISSUE THREAD

**Issue by rarog** [crazy-max/slack-portable#8]
Every x minutes a new instance is started, which works as separate process (2nd icon) and wish to login. So the new instance doesn't use same profile but creates new one in %AppData%\Slack if it doesn't exist.

#### Steps to reproduce this issue

1. Start Slack Portable
2. Work with it for some time
3. At some point of time the new instance is started

#### Expected behaviour

No new instance.

#### Actual behaviour

New instance is started, that creates new folder in %AppData%\Slack

### Configuration

Windows 10 Pro 64 bits)
![2017-09-07_09h48_35](https://user-images.githubusercontent.com/2520875/30152029-0d001612-93b2-11e7-8674-1124510945f7.png)

Slack portable 2.7.1-22 x64

### Logs

The starting of new instance isn't logged to slack-portable.log. The first and normal start is logged this way:
INFO: 2017/09/07 09:32:25.121343 main.go:46: --------
INFO: 2017/09/07 09:32:25.121343 main.go:47: Starting slack-portable...
INFO: 2017/09/07 09:32:25.121343 main.go:48: Current path: Y:\slack-portable
INFO: 2017/09/07 09:32:25.121343 main.go:60: ReadingY:\slack-portable\logs
INFO: 2017/09/07 09:32:25.121343 main.go:64: DeletedY:\slack-portable\logs\browser.log
INFO: 2017/09/07 09:32:25.122334 main.go:64: DeletedY:\slack-portable\logs\downloads
INFO: 2017/09/07 09:32:25.122334 main.go:64: DeletedY:\slack-portable\logs\renderer-11472.log
INFO: 2017/09/07 09:32:25.122334 main.go:64: DeletedY:\slack-portable\logs\webapp-login.log
INFO: 2017/09/07 09:32:25.122334 main.go:64: DeletedY:\slack-portable\logs\webview-1.log
INFO: 2017/09/07 09:32:25.122334 main.go:69: Lookup app folder in: Y:\slack-portable
INFO: 2017/09/07 09:32:25.122334 main.go:74: App folder found: app-2.7.1
INFO: 2017/09/07 09:32:25.122334 main.go:80: App path: Y:\slack-portable\app-2.7.1
INFO: 2017/09/07 09:32:25.122334 main.go:91: App executable:Y:\slack-portable\app-2.7.1\slack.exe
INFO: 2017/09/07 09:32:25.122334 main.go:92: Data path:Y:\slack-portable\data\AppData\Roaming\slack
INFO: 2017/09/07 09:32:25.122334 main.go:93: Downloads path:Y:\slack-portable\downloads
INFO: 2017/09/07 09:32:25.122334 main.go:94: Slack settings path:Y:\slack-portable\data\AppData\Roaming\slack\storage\slack-settings
INFO: 2017/09/07 09:32:25.122334 main.go:97: Create data folder Y:\slack-portable\data\AppData\Roaming\slack...
INFO: 2017/09/07 09:32:25.170570 main.go:104: Create download folder Y:\slack-portable\downloads...
INFO: 2017/09/07 09:32:25.170570 main.go:116: Update Slack settings...
ERROR: 2017/09/07 09:32:25.170570 main.go:138: Slack settings not found in: Y:\slack-portable\data\AppData\Roaming\slack\storage\slack-settings
INFO: 2017/09/07 09:32:25.170570 main.go:142: Launch Slack...

Creating Slack Application

**Comment by rarog** [comment]
I have a suspicion, that this happens, when you get a notification in thread. Perhaps the Windows 10 notification tries to communicate with Slack process and starts the new process without the trick with USERPROFILE env var.

**Comment by crazy-max** [comment]
@rarog Hi,

I dont' have this issue since the release 2.7.1-22 even while receiving notifications.
Can you post your slack settings (`data\AppData\Roaming\slack\storage\slack-settings`) ?
And do you have the ia32 or x64 release of slack-portable ?

**Comment by rarog** [comment]
I use the x64 package with 5 teams. I even deleted the data folder and logged in into every team again, but this didn't help.

Another feeling was that it might happen, when the thread or PN notification (so any direct/personal notification) comes and I'm in another slack team, triggers this behaviour. But I could't reproduce it on purpose. So there might be another factor involved.

[slack-settings.zip](https://github.com/crazy-max/slack-portable/files/1284565/slack-settings.zip)

**Comment by rarog** [comment]
I think I could reproduce it now. You have to be notified and then click on the Win10 notification above the click. This opens the normal Slack window with the notification but also starts the new Slack instance.

**Comment by crazy-max** [comment]
Ok thanks for your feedback!
What do you have here :

![image](https://user-images.githubusercontent.com/1951866/30163290-ba24927a-93d8-11e7-9304-f798cf9308ee.png)

?

**Comment by crazy-max** [comment]
Ok i was able to reproduce your issue

**Comment by rarog** [comment]
Wonderful, I really think it's some combination of how Windows sends the notification and how the portable process responds.

Just to be complete, I have identical settings as shown on your screenshot.

**Comment by crazy-max** [comment]
After disabled Flash window i don't have the issue :smile:

**Comment by rarog** [comment]
I'll do it now, too. I fear this can't be fixed on your side and the problem lies within the original Slack code, which doesn't show this behavour because of some specific implementation not expecting to deviate from standard. Not sure, where at Slack I could submit such bug.

You could perhaps write it down as "known issues".

**Comment by crazy-max** [comment]
Yes you right but i think it's an electron issue instead of a Slack one.
I will try to go deep inside electron code to find an good alternative.
Anyway thanks for your feedback!

**Comment by crazy-max** [comment]
What i can do is changing this var `windowFlashBehavior` to `never` to avoid this issue for now.

**Comment by crazy-max** [comment]
What do you think ?

**Comment by crazy-max** [comment]
What do you think ?

**Comment by crazy-max** [comment]
What do you think ?

**Comment by rarog** [comment]
It's definitely sounds like a good workaround for the time being.

**Comment by crazy-max** [comment]
To make it work we have to use the built-in Slack(s notifications :

![image](https://user-images.githubusercontent.com/1951866/30437013-e4b34a32-996d-11e7-8792-f87088ac8320.png)

![image](https://user-images.githubusercontent.com/1951866/30437031-ee9b5d96-996d-11e7-9df4-f33a64acc2e2.png)

**Comment by crazy-max** [comment]
The preference is named `notificationMethod` and we have to replace the current value `winrt` with `html` to make it work

**Comment by crazy-max** [comment]
Solved in latest 2.8.0-23
